In [1]:
import numpy as np

In [2]:
l = [1,2,4,6,8]

In [5]:
arr = np.array(l)

In [6]:
arr

array([1, 2, 4, 6, 8])

In [9]:
type(arr)

numpy.ndarray

In [10]:
arr2 = np.array([[1,2],[2,4]])

In [11]:
arr2

array([[1, 2],
       [2, 4]])

In [12]:
type(arr2)

numpy.ndarray

In [13]:
np.asarray(l)

array([1, 2, 4, 6, 8])

In [14]:
a=["aditya",3,4,"manager"]

In [23]:
arr3 =np.asanyarray(a)

In [24]:
np.asanyarray(l)

array([1, 2, 4, 6, 8])

In [25]:
np.ndim(arr3)

1

In [26]:
b = np.matrix(l)

In [27]:
b

matrix([[1, 2, 4, 6, 8]])

In [28]:
np.ndim(b)

2

In [29]:
np.asanyarray(b)

matrix([[1, 2, 4, 6, 8]])

In [32]:
np.asarray(b)

array([[1, 2, 4, 6, 8]])

In [33]:
a

['aditya', 3, 4, 'manager']

In [34]:
c=a

In [35]:
c

['aditya', 3, 4, 'manager']

In [36]:
a[0]="patil"

In [37]:
c

['patil', 3, 4, 'manager']

In [38]:
a

['patil', 3, 4, 'manager']

In [39]:
d = np.copy(a)

In [40]:
a[1]="shankar"

In [44]:
a

['patil', 'shankar', 4, 'manager']

In [45]:
d

array(['patil', '3', '4', 'manager'], dtype='<U11')

In [47]:
c

['patil', 'shankar', 4, 'manager']

In [52]:
arr4 = np.fromfunction(lambda i,j:i+j,(3,3))

In [53]:
arr4

array([[0., 1., 2.],
       [1., 2., 3.],
       [2., 3., 4.]])

In [57]:
arr5 = np.fromfunction(lambda i,j:i==j,(3,3))

In [60]:
arr5

array([[ True, False, False],
       [False,  True, False],
       [False, False,  True]])

In [61]:
iterable = (i*i for i in range(5))

In [63]:
np.fromiter(iterable,int)

array([ 0,  1,  4,  9, 16])

In [68]:
np.fromstring('234 234' , sep= ' ')

array([234., 234.])

In [69]:
np.fromstring('1,2,3,4',sep=',')

array([1., 2., 3., 4.])

# anrray data types

In [4]:
import numpy as np

In [5]:
l=  [1,3,4,5,6,7]

In [6]:
arr = np.array(l)

In [7]:
arr

array([1, 3, 4, 5, 6, 7])

In [8]:
arr.ndim

1

In [9]:
l2 = [[1,3,5,7],[2,4,6,8]]

In [12]:
arr2 = np.array(l2)

In [13]:
arr2

array([[1, 3, 5, 7],
       [2, 4, 6, 8]])

In [14]:
arr2.ndim

2

In [16]:
arr3 = np.array([[2,4,5,6,7],[64,5,6,66,4]])

In [17]:
arr3

array([[ 2,  4,  5,  6,  7],
       [64,  5,  6, 66,  4]])

In [18]:
arr3.ndim

2

In [20]:
arr.size

6

In [21]:
arr2.size

8

In [22]:
arr2.shape

(2, 4)

In [23]:
arr.shape

(6,)

In [29]:
arr4 = np.array([[1.2,3,4,5],[2.3,5,6,7]])

In [30]:
arr4

array([[1.2, 3. , 4. , 5. ],
       [2.3, 5. , 6. , 7. ]])

In [32]:
arr4.dtype

dtype('float64')

In [33]:
arr2.dtype

dtype('int32')

In [36]:
list(range(1,5))

[1, 2, 3, 4]

In [37]:
list(range(1.2,5))

TypeError: 'float' object cannot be interpreted as an integer

In [38]:
np.arange(1.2,5)

array([1.2, 2.2, 3.2, 4.2])

In [39]:
np.linspace(1,3,10)

array([1.        , 1.22222222, 1.44444444, 1.66666667, 1.88888889,
       2.11111111, 2.33333333, 2.55555556, 2.77777778, 3.        ])

In [40]:
np.zeros(2)

array([0., 0.])

In [43]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [45]:
z = np.zeros((2,3,4))

In [46]:
z

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [48]:
z.ndim

3

In [49]:
np.ones(2)

array([1., 1.])

In [51]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [54]:
o = np.ones((2,3,4,3))

In [55]:
o

array([[[[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]]],


       [[[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]]]])

In [56]:
o.ndim

4

In [58]:
o1= np.ones((2,3,4))

In [59]:
o1

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

In [60]:
o1+5

array([[[6., 6., 6., 6.],
        [6., 6., 6., 6.],
        [6., 6., 6., 6.]],

       [[6., 6., 6., 6.],
        [6., 6., 6., 6.],
        [6., 6., 6., 6.]]])

In [61]:
o1*2

array([[[2., 2., 2., 2.],
        [2., 2., 2., 2.],
        [2., 2., 2., 2.]],

       [[2., 2., 2., 2.],
        [2., 2., 2., 2.],
        [2., 2., 2., 2.]]])

In [63]:
np.empty((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [65]:
np.eye(3,4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.]])

In [67]:
np.logspace(1,2,10,base=2)

array([2.        , 2.16011948, 2.33305808, 2.5198421 , 2.72158   ,
       2.93946898, 3.1748021 , 3.42897593, 3.70349885, 4.        ])

### 

In [68]:
import pandas as pd

In [73]:
arr = np.random.rand(4,5)

In [74]:
arr

array([[0.89593706, 0.79486681, 0.98500451, 0.1657294 , 0.22872289],
       [0.80420599, 0.28882731, 0.32580075, 0.70683398, 0.57961504],
       [0.5444792 , 0.61997836, 0.73059608, 0.01008098, 0.53540992],
       [0.60174773, 0.53154975, 0.4168781 , 0.03029121, 0.64137327]])

In [75]:
dt = pd.DataFrame(arr)

In [76]:
dt

0         1         2         3         4
0  0.895937  0.794867  0.985005  0.165729  0.228723
1  0.804206  0.288827  0.325801  0.706834  0.579615
2  0.544479  0.619978  0.730596  0.010081  0.535410
3  0.601748  0.531550  0.416878  0.030291  0.641373

In [78]:
pd.DataFrame(np.random.randint(1,110 , (30,40))).to_csv('test.csv')

In [81]:
arr = np.random.randint(1,100,(3,4))

In [82]:
arr

array([[96,  5, 74, 74],
       [88, 86, 10, 45],
       [18, 73, 63, 16]])

In [83]:
arr.reshape(6,2)

array([[96,  5],
       [74, 74],
       [88, 86],
       [10, 45],
       [18, 73],
       [63, 16]])

In [85]:
arr1 = arr.reshape (4,-1)

In [86]:
arr1

array([[96,  5, 74],
       [74, 88, 86],
       [10, 45, 18],
       [73, 63, 16]])

In [87]:
arr1[1][1]

88

In [89]:
arr1[:-2,2]

array([74, 86])

In [115]:
arr3 = np.random.randint(1,100,(5,5))

In [116]:
arr3

array([[13, 99, 58, 78, 76],
       [79, 95, 39, 53,  7],
       [91, 50,  8, 74, 18],
       [71, 95, 85, 83, 28],
       [28, 46, 62, 90, 29]])

In [117]:
arr3[arr3>50]

array([99, 58, 78, 76, 79, 95, 53, 91, 74, 71, 95, 85, 83, 62, 90])

In [118]:
arr3.ndim

2

In [119]:
arr3[1:5]

array([[79, 95, 39, 53,  7],
       [91, 50,  8, 74, 18],
       [71, 95, 85, 83, 28],
       [28, 46, 62, 90, 29]])

In [120]:
arr3[1:5,[2,3]]

array([[39, 53],
       [ 8, 74],
       [85, 83],
       [62, 90]])

In [121]:
arr3[0][0]=5000

In [122]:
arr3

array([[5000,   99,   58,   78,   76],
       [  79,   95,   39,   53,    7],
       [  91,   50,    8,   74,   18],
       [  71,   95,   85,   83,   28],
       [  28,   46,   62,   90,   29]])

In [124]:
a1 = np.random.randint(1,5,(3,3))
a2 = np.random.randint(1,5,(3,3))

In [126]:
a1

array([[4, 1, 3],
       [1, 1, 2],
       [3, 3, 3]])

In [127]:
a2

array([[4, 2, 3],
       [2, 1, 2],
       [4, 2, 4]])

In [128]:
a1+a2

array([[8, 3, 6],
       [3, 2, 4],
       [7, 5, 7]])

In [129]:
a1-a2

array([[ 0, -1,  0],
       [-1,  0,  0],
       [-1,  1, -1]])

In [130]:
a1*a2

array([[16,  2,  9],
       [ 2,  1,  4],
       [12,  6, 12]])

In [131]:
a1%a2

array([[0, 1, 0],
       [1, 0, 0],
       [3, 1, 3]])

In [132]:
a1/a2

array([[1.  , 0.5 , 1.  ],
       [0.5 , 1.  , 1.  ],
       [0.75, 1.5 , 0.75]])

Matrix multiplication

In [134]:
a1@a2

array([[30, 15, 26],
       [14,  7, 13],
       [30, 15, 27]])

In [135]:
a1/0

C:\Users\adipa\AppData\Local\Temp\ipykernel_5124\1504525615.py:1: RuntimeWarning: divide by zero encountered in divide
  a1/0


array([[inf, inf, inf],
       [inf, inf, inf],
       [inf, inf, inf]])

In [136]:
a1+100

array([[104, 101, 103],
       [101, 101, 102],
       [103, 103, 103]])

In [137]:
a1**2

array([[16,  1,  9],
       [ 1,  1,  4],
       [ 9,  9,  9]])

Numpy Broadcasting

In [152]:
arr = np.zeros((4,4))

In [153]:
arr

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [157]:
row = np.array([1,2,3,4])

In [158]:
row

array([1, 2, 3, 4])

In [162]:
a = arr+row

In [163]:
row.T

array([1, 2, 3, 4])

In [165]:
a

array([[1., 2., 3., 4.],
       [1., 2., 3., 4.],
       [1., 2., 3., 4.],
       [1., 2., 3., 4.]])

In [167]:
a.T

array([[1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.],
       [4., 4., 4., 4.]])

In [170]:
arr1 = np.random.randint(1,10,(3,3))

In [171]:
arr1

array([[3, 9, 8],
       [9, 9, 4],
       [3, 4, 1]])

In [172]:
np.sqrt(arr1)

array([[1.73205081, 3.        , 2.82842712],
       [3.        , 3.        , 2.        ],
       [1.73205081, 2.        , 1.        ]])

In [173]:
np.exp(arr1)

array([[2.00855369e+01, 8.10308393e+03, 2.98095799e+03],
       [8.10308393e+03, 8.10308393e+03, 5.45981500e+01],
       [2.00855369e+01, 5.45981500e+01, 2.71828183e+00]])

In [174]:
np.log10(arr1)

array([[0.47712125, 0.95424251, 0.90308999],
       [0.95424251, 0.95424251, 0.60205999],
       [0.47712125, 0.60205999, 0.        ]])